config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :decks
  resources :cards, only: :index
  root to: "decks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
end

app/models/deck.rb
class Deck < ApplicationRecord
  has_many :cards
  belongs_to :user
  validates :title, presence: true, length: { maximum: 255 }
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :decks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @cards = Card.all
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  include Pundit::Authorization
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_deck, only: [:show, :edit, :update, :destroy]

  def index
    @decks = Deck.all
  end

  def show
  end

  def new
    @deck = Deck.new
  end

  def create
    @deck = Deck.new(deck_params)
    @deck.user = current_user
    if @deck.save
      redirect_to @deck, notice: "Deck was successfully created."
    else
      redirect_to new_deck_path, alert: "Deck was not created successfully."
    end
  end

  def edit
    authorize @deck
  end

  def update
    authorize @deck
    if @deck.update(deck_params)
      redirect_to @deck, notice: "Deck was edited successfully."
    else
      render :edit
    end
  end

  def destroy
    authorize @deck
    @deck.destroy
    redirect_to decks_path, notice: "Deck was deleted successfully."
  end

  private

  def set_deck
    @deck = Deck.find(params[:id])
  end

  def deck_params
    params.require(:deck).permit(:title, :description)
  end

  def user_not_authorized
    redirect_back(fallback_location: root_path)
    flash[:alert] = "You are not authorized to perform this action."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/cards/index.html.erb
<% if @cards.any? %>
  <div class="card-images">
    <% @cards.each do |card| %>
      <div class="card-image">
        <p>
        <%= card.id %>
        </p>
        <img src="<%= card.image %>" alt="<%= card.name %>" />
      </div>
    <% end %>
  </div>
<% else %>
  <p>No cards found.</p>
<% end %>

app/views/decks/_form.html.erb
<%= form_with(model: @deck, html: { class: "w-full max-w-md mx-auto" }) do |form| %>
  <div class="mb-4">
    <%= form.label :title, class: "block text-gray-700 font-bold mb-2" %>
    <%= form.text_field :title, class: "w-full px-3 py-2 border rounded-lg shadow-sm focus:outline-none focus:border-blue-500" %>
  </div>

  <div class="mb-4">
    <%= form.label :description, class: "block text-gray-700 font-bold mb-2" %>
    <%= form.text_area :description, class: "w-full px-3 py-2 border rounded-lg shadow-sm focus:outline-none focus:border-blue-500" %>
  </div>

  <div class="text-center">
    <%= form.submit "Submit", class: "px-4 py-2 bg-blue-500 text-white rounded-full hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50" %>
  </div>
<% end %>

app/views/decks/edit.html.erb
<%= render "form", deck: @deck %>

app/views/decks/index.html.erb
<% @decks.each do |deck| %>
  <div class="bg-white shadow-md rounded-lg p-4 mb-4">
    <h2 class="text-2xl font-semibold text-gray-800 mb-2"><%= deck.title %></h2>
    <p class="text-gray-600"><%= deck.description %></p>

    <%= link_to "View deck", deck_path(deck), class: "text-blue-500 hover:underline mt-2 inline-block" %>
  </div>
<% end %>

app/views/decks/new.html.erb
<%= form_with(model: @deck) do |form| %>
  <div>
  <%= form.label :title, style: "display: block" %>
  <%= form.text_field :title %>
  </div>

  <div>
  <%= form.label :description, style: "display: block" %>
  <%= form.text_area :description %>
  </div>

  <div>
  <%= form.submit %>
  </div>
<% end %>

app/views/decks/show.html.erb
<div class="bg-white shadow-md rounded-lg p-4 mb-4">
  <h2 class="text-2xl font-semibold text-gray-800 mb-2"><%= @deck.title %></h2>
  <p class="text-gray-600"><%= @deck.description %></p>

  <% if @deck.user == current_user %>
    <div class="mt-4">
      <%= link_to "Edit deck", edit_deck_path(@deck), class: "px-4 py-2 bg-blue-500 text-white rounded-full hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50 mr-2" %>
      <%= link_to "Delete deck", deck_path(@deck), data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete?"} , class: "px-4 py-2 bg-red-500 text-white rounded-full hover:bg-red-600 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-opacity-50" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>MagicDeckbuilder</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body class="bg-gray-100">

  <header class="bg-blue-500 p-4">
    <nav class="container mx-auto flex justify-between items-center">
      <h1 class="text-2xl font-bold text-white">MagicDeckbuilder</h1>
      <%= link_to "Cards", cards_path, class: "text-white hover:underline mr-4" %>
      <% if user_signed_in? %>
        <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "px-4 py-2 bg-red-500 text-white rounded-full hover:bg-red-600 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-opacity-50" %>
      <% else %>
        <%= link_to "Sign in", new_user_session_path, class: "text-white hover:underline mr-4" %>
        <%= link_to "Sign up", new_user_registration_path, class: "text-white hover:underline" %>
      <% end %>
    </nav>
  </header>

  <main class="container mx-auto mt-10 px-5">
    <% if flash[:notice].present? %>
      <p class="bg-green-100 text-green-800 p-2 mb-4 rounded"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert].present? %>
      <p class="bg-red-100 text-red-800 p-2 mb-4 rounded"><%= flash[:alert] %></p>
    <% end %>

    <%= yield %>
  </main>
</body>
</html>